### ISSUE TITLE
Failed to activate the atom-show-project-name package

### ISSUE THREAD

**Issue by KOE1988** [kingarthurpt/atom-show-project-name#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.11.6
**Thrown From**: [atom-show-project-name](https://github.com/kingarthurpt/atom-show-project-name) package 0.1.0

### Stack Trace

Failed to activate the atom-show-project-name package

```
At Cannot read property 'innerText' of null

TypeError: Cannot read property 'innerText' of null
    at Object.activate (/packages/atom-show-project-name/lib/main.js:11:69)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:253:25)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:99:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:215:40)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:690:42)
    at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:535:35
    at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:338:17)
    at /Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:351:17
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
```

### Commands

```
     -0:49.3.0 core:paste (input.hidden-input)
     -0:46.8.0 core:select-all (input.hidden-input)
     -0:44.9.0 core:backspace (input.hidden-input)
     -0:38.7.0 core:paste (input.hidden-input)
     -0:37.4.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.30.5 
atom-css-comb 3.3.1 
atom-html-preview 0.2.2 
atom-show-project-name 0.1.0 
autocomplete-java 1.2.7 
autocomplete-java-minus 0.14.0 
autocomplete-modules 1.7.2 
color-picker 2.2.5 
dash-syntax 0.4.1 
dash-ui 0.4.3 
logo-file-icons 1.12.0 
project-manager 3.3.5 
tree-view-open-files 0.3.0 
```

**Comment by kingarthurpt** [comment]
Thanks for reporting the issue @KOE1988 
The error should be fixed now.
